const keyObjEng = [
  [
    {
      caseDown: '`',
      caseUp: '~',
      caps: '`',
      shiftCaps: '~',
      keyCode: 192,
      code: 'Backquote',
      description: 'symbol',
    },
    {
      caseDown: '1',
      caseUp: '!',
      caps: '1',
      shiftCaps: '!',
      keyCode: 49,
      code: 'Digit1',
      description: 'digit',
    },
    {
      caseDown: '2',
      caseUp: '@',
      caps: '2',
      shiftCaps: '@',
      keyCode: 50,
      code: 'Digit2',
      description: 'digit',
    },
    {
      caseDown: '3',
      caseUp: '#',
      caps: '3',
      shiftCaps: '#',
      keyCode: 51,
      code: 'Digit3',
      description: 'digit',
    },
    {
      caseDown: '4',
      caseUp: '$',
      caps: '4',
      shiftCaps: '$',
      keyCode: 52,
      code: 'Digit4',
      description: 'digit',
    },
    {
      caseDown: '5',
      caseUp: '%',
      caps: '5',
      shiftCaps: '%',
      keyCode: 53,
      code: 'Digit5',
      description: 'digit',
    },
    {
      caseDown: '6',
      caseUp: '^',
      caps: '6',
      shiftCaps: '^',
      keyCode: 54,
      code: 'Digit6',
      description: 'digit',
    },
    {
      caseDown: '7',
      caseUp: '&',
      caps: '7',
      shiftCaps: '&',
      keyCode: 55,
      code: 'Digit7',
      description: 'digit',
    },
    {
      caseDown: '8',
      caseUp: '*',
      caps: '8',
      shiftCaps: '*',
      keyCode: 56,
      code: 'Digit8',
      description: 'digit',
    },
    {
      caseDown: '9',
      caseUp: '(',
      caps: '9',
      shiftCaps: '(',
      keyCode: 57,
      code: 'Digit9',
      description: 'digit',
    },
    {
      caseDown: '0',
      caseUp: ')',
      caps: '0',
      shiftCaps: ')',
      keyCode: 48,
      code: 'Digit0',
      description: 'digit',
    },
    {
      caseDown: '-',
      caseUp: '_',
      caps: '-',
      shiftCaps: '_',
      keyCode: 109,
      code: 'Minus',
      description: 'symbol',
    },
    {
      caseDown: '=',
      caseUp: '+',
      caps: '=',
      shiftCaps: '+',
      keyCode: 61,
      code: 'Equal',
      description: 'symbol',
    },
    {
      caseDown: 'Backspace',
      caseUp: 'Backspace',
      caps: 'Backspace',
      shiftCaps: 'Backspace',
      keyCode: 8,
      code: 'Backspace',
      description: 'function',
    },
  ],
  [
    {
      caseDown: 'Tab',
      caseUp: 'Tab',
      caps: 'Tab',
      shiftCaps: 'Tab',
      keyCode: 9,
      code: 'Tab',
      description: 'function',
    },
    {
      caseDown: 'q',
      caseUp: 'Q',
      caps: 'Q',
      shiftCaps: 'q',
      keyCode: 81,
      code: 'KeyQ',
      description: 'letter',
    },
    {
      caseDown: 'w',
      caseUp: 'W',
      caps: 'W',
      shiftCaps: 'w',
      keyCode: 87,
      code: 'KeyW',
      description: 'letter',
    },
    {
      caseDown: 'e',
      caseUp: 'E',
      caps: 'E',
      shiftCaps: 'e',
      keyCode: 69,
      code: 'KeyE',
      description: 'letter',
    },
    {
      caseDown: 'r',
      caseUp: 'R',
      caps: 'R',
      shiftCaps: 'r',
      keyCode: 82,
      code: 'KeyR',
      description: 'letter',
    },
    {
      caseDown: 't',
      caseUp: 'T',
      caps: 'T',
      shiftCaps: 't',
      keyCode: 84,
      code: 'KeyT',
      description: 'letter',
    },
    {
      caseDown: 'y',
      caseUp: 'Y',
      caps: 'Y',
      shiftCaps: 'y',
      keyCode: 89,
      code: 'KeyY',
      description: 'letter',
    },
    {
      caseDown: 'u',
      caseUp: 'U',
      caps: 'U',
      shiftCaps: 'u',
      keyCode: 85,
      code: 'KeyU',
      description: 'letter',
    },
    {
      caseDown: 'i',
      caseUp: 'I',
      caps: 'I',
      shiftCaps: 'i',
      keyCode: 73,
      code: 'KeyI',
      description: 'letter',
    },
    {
      caseDown: 'o',
      caseUp: 'O',
      caps: 'O',
      shiftCaps: 'o',
      keyCode: 79,
      code: 'KeyO',
      description: 'letter',
    },
    {
      caseDown: 'p',
      caseUp: 'P',
      caps: 'P',
      shiftCaps: 'p',
      keyCode: 80,
      code: 'KeyP',
      description: 'letter',
    },
    {
      caseDown: '[',
      caseUp: '{',
      caps: '[',
      shiftCaps: '{',
      keyCode: 160,
      code: 'BracketLeft',
      description: 'symbol',
    },
    {
      caseDown: ']',
      caseUp: '}',
      caps: ']',
      shiftCaps: '}',
      keyCode: 221,
      code: 'BracketRight',
      description: 'symbol',
    },
    {
      caseDown: '\\',
      caseUp: '|',
      caps: '\\',
      shiftCaps: '|',
      keyCode: 220,
      code: 'Backslash',
      description: 'symbol',
    },
    {
      caseDown: 'Delete',
      caseUp: 'Delete',
      caps: 'Delete',
      shiftCaps: 'Delete',
      keyCode: 46,
      code: 'Delete',
      description: 'function',
    },
  ],
  [
    {
      caseDown: 'CapsLock',
      caseUp: 'CapsLock',
      caps: 'CapsLock',
      shiftCaps: 'CapsLock',
      keyCode: 20,
      code: 'CapsLock',
      description: 'function',
    },
    {
      caseDown: 'a',
      caseUp: 'A',
      caps: 'A',
      shiftCaps: 'a',
      keyCode: 65,
      code: 'KeyA',
      description: 'letter',
    },
    {
      caseDown: 's',
      caseUp: 'S',
      caps: 'S',
      shiftCaps: 's',
      keyCode: 83,
      code: 'KeyS',
      description: 'letter',
    },
    {
      caseDown: 'd',
      caseUp: 'D',
      caps: 'D',
      shiftCaps: 'd',
      keyCode: 68,
      code: 'KeyD',
      description: 'letter',
    },
    {
      caseDown: 'f',
      caseUp: 'F',
      caps: 'F',
      shiftCaps: 'f',
      keyCode: 70,
      code: 'KeyF',
      description: 'letter',
    },
    {
      caseDown: 'g',
      caseUp: 'G',
      caps: 'G',
      shiftCaps: 'g',
      keyCode: 71,
      code: 'KeyG',
      description: 'letter',
    },
    {
      caseDown: 'h',
      caseUp: 'H',
      caps: 'H',
      shiftCaps: 'h',
      keyCode: 72,
      code: 'KeyH',
      description: 'letter',
    },
    {
      caseDown: 'j',
      caseUp: 'J',
      caps: 'J',
      shiftCaps: 'j',
      keyCode: 74,
      code: 'KeyJ',
      description: 'letter',
    },
    {
      caseDown: 'k',
      caseUp: 'K',
      caps: 'K',
      shiftCaps: 'k',
      keyCode: 75,
      code: 'KeyK',
      description: 'letter',
    },
    {
      caseDown: 'l',
      caseUp: 'L',
      caps: 'L',
      shiftCaps: 'l',
      keyCode: 76,
      code: 'KeyL',
      description: 'letter',
    },
    {
      caseDown: ';',
      caseUp: ':',
      caps: ';',
      shiftCaps: ':',
      keyCode: 59,
      code: 'Semicolon',
      description: 'symbol',
    },
    {
      caseDown: "'",
      caseUp: '"',
      caps: "'",
      shiftCaps: '"',
      keyCode: 222,
      code: 'Quote',
      description: 'symbol',
    },
    {
      caseDown: 'Enter',
      caseUp: 'Enter',
      caps: 'Enter',
      shiftCaps: 'Enter',
      keyCode: 13,
      code: 'Enter',
      description: 'function',
    },
  ],
  [
    {
      caseDown: 'Shift',
      caseUp: 'Shift',
      caps: 'Shift',
      shiftCaps: 'Shift',
      keyCode: 16,
      code: 'ShiftLeft',
      description: 'function',
    },
    {
      caseDown: 'z',
      caseUp: 'Z',
      caps: 'Z',
      shiftCaps: 'z',
      keyCode: 90,
      code: 'KeyZ',
      description: 'letter',
    },
    {
      caseDown: 'x',
      caseUp: 'X',
      caps: 'X',
      shiftCaps: 'x',
      keyCode: 88,
      code: 'KeyX',
      description: 'letter',
    },
    {
      caseDown: 'c',
      caseUp: 'C',
      caps: 'C',
      shiftCaps: 'c',
      keyCode: 67,
      code: 'KeyC',
      description: 'letter',
    },
    {
      caseDown: 'v',
      caseUp: 'V',
      caps: 'V',
      shiftCaps: 'v',
      keyCode: 86,
      code: 'KeyV',
      description: 'letter',
    },
    {
      caseDown: 'b',
      caseUp: 'B',
      caps: 'B',
      shiftCaps: 'b',
      keyCode: 66,
      code: 'KeyB',
      description: 'letter',
    },
    {
      caseDown: 'n',
      caseUp: 'N',
      caps: 'N',
      shiftCaps: 'n',
      keyCode: 78,
      code: 'KeyN',
      description: 'letter',
    },
    {
      caseDown: 'm',
      caseUp: 'M',
      caps: 'M',
      shiftCaps: 'm',
      keyCode: 77,
      code: 'KeyM',
      description: 'letter',
    },
    {
      caseDown: ',',
      caseUp: '<',
      caps: ',',
      shiftCaps: '<',
      keyCode: 108,
      code: 'Comma',
      description: 'symbol',
    },
    {
      caseDown: '.',
      caseUp: '>',
      caps: '.',
      shiftCaps: '>',
      keyCode: 190,
      code: 'Period',
      description: 'symbol',
    },
    {
      caseDown: '/',
      caseUp: '?',
      caps: '/',
      shiftCaps: '?',
      keyCode: 191,
      code: 'Slash',
      description: 'symbol',
    },
    {
      caseDown: '▲',
      caseUp: '▲',
      caps: '▲',
      shiftCaps: '▲',
      keyCode: 38,
      code: 'ArrowUp',
      description: 'symbol',
    },
    {
      caseDown: 'Shift',
      caseUp: 'Shift',
      caps: 'Shift',
      shiftCaps: 'Shift',
      keyCode: 16,
      code: 'ShiftRight',
      description: 'function',
    },
  ],
  [
    {
      caseDown: 'CTRL',
      caseUp: 'CTRL',
      caps: 'CTRL',
      shiftCaps: 'CTRL',
      keyCode: 17,
      code: 'ControlLeft',
      description: 'function',
    },
    {
      caseDown: 'Win',
      caseUp: 'Win',
      caps: 'Win',
      shiftCaps: 'Win',
      keyCode: 91,
      code: 'MetaLeft',
      description: 'function',
    },
    {
      caseDown: 'Alt',
      caseUp: 'Alt',
      caps: 'Alt',
      shiftCaps: 'Alt',
      keyCode: 18,
      code: 'AltLeft',
      description: 'function',
    },
    {
      caseDown: ' ',
      caseUp: ' ',
      caps: ' ',
      shiftCaps: ' ',
      keyCode: 32,
      code: 'Space',
      description: 'symbol',
    },
    {
      caseDown: 'Alt',
      caseUp: 'Alt',
      caps: 'Alt',
      shiftCaps: 'Alt',
      keyCode: 18,
      code: 'AltRight',
      description: 'function',
    },
    {
      caseDown: '◄',
      caseUp: '◄',
      caps: '◄',
      shiftCaps: '◄',
      keyCode: 37,
      code: 'ArrowLeft',
      description: 'symbol',
    },
    {
      caseDown: '▼',
      caseUp: '▼',
      caps: '▼',
      shiftCaps: '▼',
      keyCode: 40,
      code: 'ArrowDown',
      description: 'symbol',
    },
    {
      caseDown: '►',
      caseUp: '►',
      caps: '►',
      shiftCaps: '►',
      keyCode: 39,
      code: 'ArrowRight',
      description: 'symbol',
    },
    {
      caseDown: 'CTRL',
      caseUp: 'CTRL',
      caps: 'CTRL',
      shiftCaps: 'CTRL',
      keyCode: 17,
      code: 'ControlRight',
      description: 'function',
    },
  ],
];
export default keyObjEng;
