const keyObjRus = [
  [
    {
      caseDown: 'ё',
      caseUp: 'Ё',
      caps: 'Ё',
      shiftCaps: 'ё',
      keyCode: 192,
      code: 'Backquote',
      description: 'letter',
    },
    {
      caseDown: '1',
      caseUp: '!',
      caps: '1',
      shiftCaps: '!',
      keyCode: 49,
      code: 'Digit1',
      description: 'digit',
    },
    {
      caseDown: '2',
      caseUp: '"',
      caps: '2',
      shiftCaps: '"',
      keyCode: 50,
      code: 'Digit2',
      description: 'digit',
    },
    {
      caseDown: '3',
      caseUp: '№',
      caps: '3',
      shiftCaps: '№',
      keyCode: 51,
      code: 'Digit3',
      description: 'digit',
    },
    {
      caseDown: '4',
      caseUp: ';',
      caps: '4',
      shiftCaps: ';',
      keyCode: 52,
      code: 'Digit4',
      description: 'digit',
    },
    {
      caseDown: '5',
      caseUp: '%',
      caps: '5',
      shiftCaps: '%',
      keyCode: 53,
      code: 'Digit5',
      description: 'digit',
    },
    {
      caseDown: '6',
      caseUp: ':',
      caps: '6',
      shiftCaps: ':',
      keyCode: 54,
      code: 'Digit6',
      description: 'digit',
    },
    {
      caseDown: '7',
      caseUp: '?',
      caps: '7',
      shiftCaps: '?',
      keyCode: 55,
      code: 'Digit7',
      description: 'digit',
    },
    {
      caseDown: '8',
      caseUp: '*',
      caps: '8',
      shiftCaps: '*',
      keyCode: 56,
      code: 'Digit8',
      description: 'digit',
    },
    {
      caseDown: '9',
      caseUp: '(',
      caps: '9',
      shiftCaps: '(',
      keyCode: 57,
      code: 'Digit9',
      description: 'digit',
    },
    {
      caseDown: '0',
      caseUp: ')',
      caps: '0',
      shiftCaps: ')',
      keyCode: 48,
      code: 'Digit0',
      description: 'digit',
    },
    {
      caseDown: '-',
      caseUp: '_',
      caps: '-',
      shiftCaps: '_',
      keyCode: 109,
      code: 'Minus',
      description: 'simbol',
    },
    {
      caseDown: '=',
      caseUp: '+',
      caps: '=',
      shiftCaps: '+',
      keyCode: 61,
      code: 'Equal',
      description: 'simbol',
    },
    {
      caseDown: 'Backspace',
      caseUp: 'Backspace',
      caps: 'Backspace',
      shiftCaps: 'Backspace',
      keyCode: 8,
      code: 'Backspace',
      description: 'function',
    },
  ],
  [
    {
      caseDown: 'Tab',
      caseUp: 'Tab',
      caps: 'Tab',
      shiftCaps: 'Tab',
      keyCode: 9,
      code: 'Tab',
      description: 'function',
    },
    {
      caseDown: 'й',
      caseUp: 'Й',
      caps: 'Й',
      shiftCaps: 'й',
      keyCode: 81,
      code: 'KeyQ',
      description: 'letter',
    },
    {
      caseDown: 'ц',
      caseUp: 'Ц',
      caps: 'Ц',
      shiftCaps: 'ц',
      keyCode: 87,
      code: 'KeyW',
      description: 'letter',
    },
    {
      caseDown: 'у',
      caseUp: 'У',
      caps: 'У',
      shiftCaps: 'у',
      keyCode: 69,
      code: 'KeyE',
      description: 'letter',
    },
    {
      caseDown: 'к',
      caseUp: 'К',
      caps: 'К',
      shiftCaps: 'к',
      keyCode: 82,
      code: 'KeyR',
      description: 'letter',
    },
    {
      caseDown: 'е',
      caseUp: 'Е',
      caps: 'Е',
      shiftCaps: 'е',
      keyCode: 84,
      code: 'KeyT',
      description: 'letter',
    },
    {
      caseDown: 'н',
      caseUp: 'Н',
      caps: 'Н',
      shiftCaps: 'н',
      keyCode: 89,
      code: 'KeyY',
      description: 'letter',
    },
    {
      caseDown: 'г',
      caseUp: 'Г',
      caps: 'Г',
      shiftCaps: 'г',
      keyCode: 85,
      code: 'KeyU',
      description: 'letter',
    },
    {
      caseDown: 'ш',
      caseUp: 'Ш',
      caps: 'Ш',
      shiftCaps: 'ш',
      keyCode: 73,
      code: 'KeyI',
      description: 'letter',
    },
    {
      caseDown: 'щ',
      caseUp: 'Щ',
      caps: 'Щ',
      shiftCaps: 'щ',
      keyCode: 79,
      code: 'KeyO',
      description: 'letter',
    },
    {
      caseDown: 'з',
      caseUp: 'З',
      caps: 'З',
      shiftCaps: 'з',
      keyCode: 80,
      code: 'KeyP',
      description: 'letter',
    },
    {
      caseDown: 'х',
      caseUp: 'Х',
      caps: 'Х',
      shiftCaps: 'х',
      keyCode: 160,
      code: 'BracketLeft',
      description: 'letter',
    },
    {
      caseDown: 'ъ',
      caseUp: 'Ъ',
      caps: 'Ъ',
      shiftCaps: 'ъ',
      keyCode: 221,
      code: 'BracketRight',
      description: 'letter',
    },
    {
      caseDown: '\\',
      caseUp: '/',
      caps: '\\',
      shiftCaps: '/',
      keyCode: 220,
      code: 'Backslash',
      description: 'symbol',
    },
    {
      caseDown: 'Delete',
      caseUp: 'Delete',
      caps: 'Delete',
      shiftCaps: 'Delete',
      keyCode: 46,
      code: 'Delete',
      description: 'function',
    },
  ],
  [
    {
      caseDown: 'CapsLock',
      caseUp: 'CapsLock',
      caps: 'CapsLock',
      shiftCaps: 'CapsLock',
      keyCode: 20,
      code: 'CapsLock',
      description: 'function',
    },
    {
      caseDown: 'ф',
      caseUp: 'Ф',
      caps: 'Ф',
      shiftCaps: 'ф',
      keyCode: 65,
      code: 'KeyA',
      description: 'letter',
    },
    {
      caseDown: 'ы',
      caseUp: 'Ы',
      caps: 'Ы',
      shiftCaps: 'ы',
      keyCode: 83,
      code: 'KeyS',
      description: 'letter',
    },
    {
      caseDown: 'в',
      caseUp: 'В',
      caps: 'В',
      shiftCaps: 'в',
      keyCode: 68,
      code: 'KeyD',
      description: 'letter',
    },
    {
      caseDown: 'а',
      caseUp: 'А',
      caps: 'А',
      shiftCaps: 'а',
      keyCode: 70,
      code: 'KeyF',
      description: 'letter',
    },
    {
      caseDown: 'п',
      caseUp: 'П',
      caps: 'П',
      shiftCaps: 'п',
      keyCode: 71,
      code: 'KeyG',
      description: 'letter',
    },
    {
      caseDown: 'р',
      caseUp: 'Р',
      caps: 'Р',
      shiftCaps: 'р',
      keyCode: 72,
      code: 'KeyH',
      description: 'letter',
    },
    {
      caseDown: 'о',
      caseUp: 'О',
      caps: 'О',
      shiftCaps: 'о',
      keyCode: 74,
      code: 'KeyJ',
      description: 'letter',
    },
    {
      caseDown: 'л',
      caseUp: 'Л',
      caps: 'Л',
      shiftCaps: 'л',
      keyCode: 75,
      code: 'KeyK',
      description: 'letter',
    },
    {
      caseDown: 'д',
      caseUp: 'Д',
      caps: 'Д',
      shiftCaps: 'д',
      keyCode: 76,
      code: 'KeyL',
      description: 'letter',
    },
    {
      caseDown: 'ж',
      caseUp: 'Ж',
      caps: 'Ж',
      shiftCaps: 'ж',
      keyCode: 59,
      code: 'Semicolon',
      description: 'letter',
    },
    {
      caseDown: 'э',
      caseUp: 'Э',
      caps: 'Э',
      shiftCaps: 'э',
      keyCode: 222,
      code: 'Quote',
      description: 'letter',
    },
    {
      caseDown: 'Enter',
      caseUp: 'Enter',
      caps: 'Enter',
      shiftCaps: 'Enter',
      keyCode: 13,
      code: 'Enter',
      description: 'function',
    },
  ],
  [
    {
      caseDown: 'Shift',
      caseUp: 'Shift',
      caps: 'Shift',
      shiftCaps: 'Shift',
      keyCode: 16,
      code: 'ShiftLeft',
      description: 'function',
    },
    {
      caseDown: 'я',
      caseUp: 'Я',
      caps: 'Я',
      shiftCaps: 'я',
      keyCode: 90,
      code: 'KeyZ',
      description: 'letter',
    },
    {
      caseDown: 'ч',
      caseUp: 'Ч',
      caps: 'Ч',
      shiftCaps: 'ч',
      keyCode: 88,
      code: 'KeyX',
      description: 'letter',
    },
    {
      caseDown: 'с',
      caseUp: 'С',
      caps: 'С',
      shiftCaps: 'с',
      keyCode: 67,
      code: 'KeyC',
      description: 'letter',
    },
    {
      caseDown: 'м',
      caseUp: 'М',
      caps: 'М',
      shiftCaps: 'м',
      keyCode: 86,
      code: 'KeyV',
      description: 'letter',
    },
    {
      caseDown: 'и',
      caseUp: 'И',
      caps: 'И',
      shiftCaps: 'и',
      keyCode: 66,
      code: 'KeyB',
      description: 'letter',
    },
    {
      caseDown: 'т',
      caseUp: 'Т',
      caps: 'Т',
      shiftCaps: 'т',
      keyCode: 78,
      code: 'KeyN',
      description: 'letter',
    },
    {
      caseDown: 'ь',
      caseUp: 'Ь',
      caps: 'Ь',
      shiftCaps: 'ь',
      keyCode: 77,
      code: 'KeyM',
      description: 'letter',
    },
    {
      caseDown: 'б',
      caseUp: 'Б',
      caps: 'Б',
      shiftCaps: 'б',
      keyCode: 108,
      code: 'Comma',
      description: 'letter',
    },
    {
      caseDown: 'ю',
      caseUp: 'Ю',
      caps: 'Ю',
      shiftCaps: 'ю',
      keyCode: 190,
      code: 'Period',
      description: 'letter',
    },
    {
      caseDown: '.',
      caseUp: ',',
      caps: '.',
      shiftCaps: ',',
      keyCode: 191,
      code: 'Slash',
      description: 'symbol',
    },
    {
      caseDown: '▲',
      caseUp: '▲',
      caps: '▲',
      shiftCaps: '▲',
      keyCode: 38,
      code: 'ArrowUp',
      description: 'symbol',
    },
    {
      caseDown: 'Shift',
      caseUp: 'Shift',
      caps: 'Shift',
      shiftCaps: 'Shift',
      keyCode: 16,
      code: 'ShiftRight',
      description: 'function',
    },
  ],
  [
    {
      caseDown: 'CTRL',
      caseUp: 'CTRL',
      caps: 'CTRL',
      shiftCaps: 'CTRL',
      keyCode: 17,
      code: 'ControlLeft',
      description: 'function',
    },
    {
      caseDown: 'Win',
      caseUp: 'Win',
      caps: 'Win',
      shiftCaps: 'Win',
      keyCode: 91,
      code: 'MetaLeft',
      description: 'function',
    },
    {
      caseDown: 'Alt',
      caseUp: 'Alt',
      caps: 'Alt',
      shiftCaps: 'Alt',
      keyCode: 18,
      code: 'AltLeft',
      description: 'function',
    },
    {
      caseDown: ' ',
      caseUp: ' ',
      caps: ' ',
      shiftCaps: ' ',
      keyCode: 32,
      code: 'Space',
      description: 'symbol',
    },
    {
      caseDown: 'Alt',
      caseUp: 'Alt',
      caps: 'Alt',
      shiftCaps: 'Alt',
      keyCode: 18,
      code: 'AltRight',
      description: 'function',
    },
    {
      caseDown: '◄',
      caseUp: '◄',
      caps: '◄',
      shiftCaps: '◄',
      keyCode: 37,
      code: 'ArrowLeft',
      description: 'symbol',
    },
    {
      caseDown: '▼',
      caseUp: '▼',
      caps: '▼',
      shiftCaps: '▼',
      keyCode: 40,
      code: 'ArrowDown',
      description: 'symbol',
    },
    {
      caseDown: '►',
      caseUp: '►',
      caps: '►',
      shiftCaps: '►',
      keyCode: 39,
      code: 'ArrowRight',
      description: 'symbol',
    },
    {
      caseDown: 'CTRL',
      caseUp: 'CTRL',
      caps: 'CTRL',
      shiftCaps: 'CTRL',
      keyCode: 17,
      code: 'ControlRight',
      description: 'function',
    },
  ],
];
export default keyObjRus;
